version: '3.8'

services:
  backend:
    build: ./server
    container_name: fitai-backend
    ports:
      - "8000:8000"
    env_file: ./server/.env
    volumes:
      - ./server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./client
    container_name: fitai-frontend
    ports:
      - "5173:5173"
    env_file: ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend